# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.3.0"

[source]
workspace = "."
paths = ["src/"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["laravel"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
prefer-static-closure = { enabled = false }
halstead = { effort-threshold = 7000 }
too-many-methods = { threshold=40 }
cyclomatic-complexity = { threshold=25 }
prefer-first-class-callable = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
#todo: enable when fixed: src/Domain/Entities/Entity.php:22:1
kan-defect = { enabled = false }
inline-variable-return = { enabled = false }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
memoize-properties = true
allow-possibly-undefined-array-keys = true
check-throws = false
check-missing-override = false
find-unused-parameters = false
strict-list-index-checks = false
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true

[guard.perimeter]
# Defines the architectural layers from core to infrastructure.
layering = [
    "Lava83\\LaravelDdd\\Domain",
    "Lava83\\LaravelDdd\\Application",
    "Lava83\\LaravelDdd\\Facades",
    "Lava83\\LaravelDdd\\Infrastructure",
]

# Creates reusable aliases for groups of namespaces.
[guard.perimeter.layers]
core = ["@native", "Psl\\**", "Ramsey\\**", "Illuminate\\**", "Illuminate\\**", "Carbon\\**", "libphonenumber\\**", "Lava83\\LaravelDdd\\Infrastructure\\Models\\Model"]
psr = ["Psr\\**"]
framework = ["Symfony\\**", "GuzzleHttp\\**", "Monolog\\**", "Doctrine\\**", "Spatie\\**"]

[[guard.perimeter.rules]]
namespace = "Lava83\\LaravelDdd\\Domain"
permit = ["@layer:core"]

[[guard.perimeter.rules]]
namespace = "Lava83\\LaravelDdd\\Application"
permit = ["@layer:core", "@layer:psr"]

[[guard.perimeter.rules]]
namespace = "Lava83\\LaravelDdd\\Infrastructure"
permit = ["@layer:core", "@layer:psr", "@layer:framework"]

[[guard.perimeter.rules]]
namespace = "Lava83\\LaravelDdd\\Tests"
permit = ["@all"]

[[guard.structural.rules]]
on               = "Lava83\\LaravelDdd\\Application\\**\\Controller\\**"
target           = "class"
must-be-named    = "*Controller"
must-be-final    = true
must-be-readonly = true
reason           = "Controllers must be final and follow naming conventions."

[[guard.structural.rules]]
on               = "Lava83\\LaravelDdd\\Application\\**\\Resources\\**"
target           = "class"
must-be-named    = "*Resource"
must-be-final    = true
must-extend      = "Illuminate\\Http\\Resources\\Json\\JsonResource"
reason           = "Resources must be final and follow naming conventions."

[[guard.structural.rules]]
on          = "Lava83\\LaravelDdd\\Domain\\**\\Enum\\**"
must-be     = ["enum"]
reason      = "This namespace is designated for enums only."
