# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.3.0"

[source]
workspace = "."
paths = ["src/"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["laravel"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
prefer-static-closure = { enabled = false }
halstead = { effort-threshold = 7000 }
too-many-methods = { threshold=40 }
cyclomatic-complexity = { threshold=25 }
prefer-first-class-callable = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
#todo: enable when fixed: src/Domain/Entities/Entity.php:22:1
kan-defect = { enabled = false }
inline-variable-return = { enabled = false }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
memoize-properties = true
allow-possibly-undefined-array-keys = true
check-throws = false
check-missing-override = false
find-unused-parameters = false
strict-list-index-checks = false
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true
